### ISSUE TITLE
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by daidaiworm** [Sellix/python-sdk#2]
Python: 3.10.9
Sellix: sellix-python-sdk  1.0.5

replaced <YOUR_API_KEY> and <MERCHANT_NAME> with my own.
 encounter this issue: 
**requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)**

```
from sellix import Sellix

# pass <MERCHANT_NAME> only if you need to be authenticated as an additional store

client = Sellix("<YOUR_API_KEY>", "<MERCHANT_NAME>")

try:
    products = client.get_products()
except Sellix.SellixException as e:
    print(e)
```

**Comment by ghost** [comment]
aslo ImportError: cannot import name 'Sellix' from partially initialized module 'sellix' (most likely due to a circular import)
